/**
 * LCR 019. 验证回文串 II
 *
 * 给定一个非空字符串 s，请判断如果 最多 从字符串中删除一个字符能否得到一个回文字符串。
 *
 * 示例 1:
 * 输入: s = "aba"
 * 输出: true
 *
 * 示例 2:
 * 输入: s = "abca"
 * 输出: true
 * 解释: 可以删除 "c" 字符 或者 "b" 字符
 *
 * 示例 3:
 * 输入: s = "abc"
 * 输出: false
 *
 * 提示:
 * 1 <= s.length <= 105
 * s 由小写英文字母组成
 *
 * 注意：本题与主站 680 题相同： https://leetcode-cn.com/problems/valid-palindrome-ii/
 */

/**
 * @param {string} s
 * @return {boolean}
 */
var validPalindrome = function (s) {
  if (s.length <= 1 || s === s.split('').reverse().join('')) return true

  for (let i = 0, j = s.length - 1; i < j; i++, j--) {
    if (s[i] !== s[j]) {
      return (
        s.slice(i, j) === s.slice(i, j).split('').reverse().join('') ||
        s.slice(i + 1, j + 1) ===
          s
            .slice(i + 1, j + 1)
            .split('')
            .reverse()
            .join('')
      )
    }
  }
  return false
}

console.log(validPalindrome('cxcaac'))
console.log(validPalindrome('aba'))
console.log(validPalindrome('abca'))
console.log(validPalindrome('abc'))
console.log(
  validPalindrome(
    'ffauugjyulaqbbiompuervdpseosxycadcbqrxfiavbhtwwmesdyqqrohqbckgrvemtiwjmfspnlqrqlnugxuprtojqawmebkrquijqooiqyuuxduxnfrryyuhsaegwbkfxilmisspeqrcxnmslvpcbjiesdmzfzdwnzpjkogmnomlarvunoacradtwyfcnbwuoevqjotgtoubpzxresjzldmzpsyicrzgsvtxkxzvrgxdbqfcicbwlabzgtpnjidfgzuwxyglftbzirdlkxohebyceyqxigexttrddalsxijtboijkugqwipdiddhtctyybpxvkideakrvntgmlxmcwsurvdsuvhcvmnwrqtgsirydsoycooopkziuxejasdxsdwalckdhkgdwpajbosrqqrkckibifcokhuhsdtkrooqoositozdqnoaljlgamhhrmlynigwjfkcsndzzmeisfoewtacxjqcjdlprlwrivsazpajcbrlznrxsmqywzxuhbyescklxunlldpnpuigmxnlirewsjpahkkizinubljrjpflysdzboecexptznftbnxnkuzflanypgpkebfrmnhoqgdynwnegxfzeqefsoagxceekpeentlzbsyluupegmgdywjksozqdsdfldnfpqafzzlqonprvrvowrlwjoohpzbcylqtpfxjvowljmjxcjqpxotmlvvbsnpytujcpxydzyjubvqbovgtkjlenrhoiqzwtaomwleuiqlyzwwvsghqafjrtdzqsrvzgbozqqfqijsldawnozatyrzgypzcywftrksunpoqkmuwljrpkweeujoytkrgpsxnliynvenzsrnyhqoyjngdsxojvmysxsyuoqsjbmhyqwbgyjaacxfzdmdqjhceohyijonzadvqhvmjgpqeiugbowaafsucuuyyyqhhcsmlqygqgpjbjrmqghtypwumtkijyhpdpmpoqtoeijcpseriqyxmejvkjdqwzvrvdfkcjkdgbmzgvgdqbgmsfqpwjdbgiygovxdbtqckwmmtnbxqriyatddsywpsuupgcwwamuyjxlztgweilqkbhuvgcbslhkkjlawqxrixgxtbnkspptwrkgjcmrpnoclcammjzsuvunbpmqonxxhmsvtugjtjwgtzaqlghjiboemhglkmftoctbzzicdqhdiaybpnlefhyqukfwrvfvmafkylclzviyikdnaqhsgmiyxgycuukqodpinekjjwtrnfkgdlebkrmqctcghqapqkqeqwxpwurdhhcbwjosfsnrczyuycapdrwqrfxrgionogtxuqtimculhzofddpqillwjlazsybxuvyuhbytgiykbajkxrhkjcxifuhiwkshovtnrwfyqpgjtoqvtjekvmhguuqfoeamgurihtdgnezxtpoaruyfoptkirqfqgthfisvlkzggivsxjwiglzculkuszyqnuunbtirqqkxminiybqobdzanjtxyhsviibnngmzvqnrbgxdvizsfdtzzaepsphqnidxjmuyikefpcflzyrsjhsrxffkkvbihtogjybceocqfiqjcgojcmsswqfizhnjaxsmbkrboldnpqowjgrrjsnrysvoymrboymgqtzjldlskfcvmtkcswrfdyqgcfbxzwnnhkcbofluyrpbslhwzinvzshnevnkfkyixtwgkutlvjmbmjubcxkkhrmcvrpcyazsumapwjxahiovqxucokwnoacahzxjnonxljobsmiwvplskbkdubkhwxxufvoqftqhjlzwdiuikzccwtzsgftnbvtblduunpnhrqtuuehtugwjlgqebhjdxafeomkhdantpyouumztmbiuqnxsxiooqxfcxwqiioyibobrhwkbpaxrtixzesfpowjnmilsizpauvjnrfcvjbpjuhyasptekupyzqvzpypbewazhnepnufkfynqnfbwmlprhyrtjjndvsemqelfafqflvqmoqijfifrttcjamqfaulxpomlhwghdkdyshetxupovnhcaqjtrqmdhgynqhaqimwnangyyghppxgcyijrocvzgkofpchdnehaegeljgfknvertwfffwqctendueagjylmmmxgogqygsehjeorpjddafmypvafaqlymivsnejkozwfmxzvqyskgfqotoeltgwlbwqpszjdmvcyigcrjwqpujsedqudjuwuhypthpuddzpgihabgspownlpgrkqmcgllgctqtftdeohpbucdsdlhedejwzknapwslzxlimkwfwimfbzdlguokttgnioztpnpikyclfaeyzcbgxlocihyrocvxtbsjgrycvtzyapyhcxfioginmctnwwnzmfukblowedsptstnnhtgnrfjsdhfrscrhcebrgkehhpjoglkjmrdondurcomxqzqkfeytzxfqvaxfbkskhkyiczqygjswbjaxouuzqsooahhjrplpdeccpvgfdhzgcyqdiggrbzfpsridlohooyadqexwkijqyrfcagwzftnmdmrfcqwolfhzyobswhuslxbfnhwwepryyqyjdfmmwtmgwwimytcttmhnrrcseeikrkspgpsplxbtrvabzrjvrrpcmlhzlxhlwxpxbveqiwoveiusdnmldagoffsllxwnqimyvingnxtmysfivlexionokuderlhfioolpdgazncmfjwqujvpwyopcuwwihriomisttlqrljxcwywopecjwohevujfovhhkzqcfiatpbypqzfztqziagxdkokwvhsscnlhosfyjagzysbyictofjirvksnczapynbzfughfemrmgvzxvhjuijifhaladrkfvvqbtzppvbrrecrwyvjpglscgmeuovubgwvshstvbvdwdavfyhpdxlhkcrycpuciaxkwtlszcjpqavexiahioofcdqywclksmdxbtvniqlljshzmlyckhdtfsyksxbgpljzdlouojvnlasfwfatwgpfbaoixidjaapipddqjesagwjmmpfobvazwfrskrzoowatcbdvaamnjmqzdmgozotdlbxkokmekwkmlwgfhxxfogqwsomcpdpmcmnywzjrchnmqhbipbyvwblcdndekktekpuplhmzjniiunnyerpxsqsgbofgcfwkmwtsxngolmfwtmcazvuluhymbvsgqhtresxeigptthuvfnbwwjuzrtvbggvvzbfinvucwzxrkxsxxgbxojwefknmmhngwgpbzfqikdmmwslbiabvixtmmbhqwopzvynoizgfafliuihibhenrfhscmhdmufrwjfvuutwxnrkqwawndydxxiqfxczitmjgqekophrvnntmxybbojjktpvbrrgqmtcksiyylmvnjvycflwvkvwdoaqhmfvqglzlzjjxwcxdxoohxrexhoacylujwcfjzqgitjkqprcsxsfphoajnwcwgpubwjterzywlmldxauiohlywlvsaacjdxbdhbvfvymgrfubdxkwvrqitrexftfmavjklinvopsxbhbndgfxdmmaesgpyunpiijsavkmqnyltzdqwbhtjcgruuoltzogpnbwesomuhzavlrxncwkufqwyjeklksjqtstmpvgsdmtkulefdijfutltkgwuawemizieicjsoelagmlhdvmevmysdstepwxhtmhpxiaiwtuddgrhsabtytpwbuzzauvddrgfxuyuccxoweqtphwhsevrhaamlnxilxeqzjhrmofxkstldmdgvjkduwwqzxxgzacfipcigtdtmwjcmipjvrarfefvvoxpuicdxttrpykonpidgshgiifiafugzzedhithqzfeetmvabbjyhlethldcixvjnewvdjrdzkntaqrfpovbhwdjoyjkmbutmbidskrpuycnawtbadoiunipfxsggmcfrcsyerwmsvimcidqxwojfacdqlmoxjpgagqjpotnoytfchdhzfcwpvgyxxzbwvmqidojffysevzszjhexqwbekjyknhrcfklcycnrytjynklmvdqdrxnxgwakoiexldypfyvueeyqfgpfiyhbrafsvknhdqsbrpgkisvgoyecarmhjfswwofvssgixjsvkjnhwufnmvugeufwjlaekyguypqlvgqvdtwhayqrlclscfyjwhbfqylbkuwwogkyatqjvglygzyjdhsikybgbyroykmcjqkfrljgtbvmupetgnnwlzqxxhzxpvgwviobjltptscaidkkgfadkytyknltgkeknjnyijcgwkpdnbbwawjvssawcjjuwfiplojqaavuaccxsieemvakxxkiuvtsvwiibrixmjbgrarmmllwxufwxcqmaeawkyrsgxnuzwjpfidlgaemqzyhgkhgmcikouuneqbdfhngcllurqaqddcnkaaesnwsolgjahnwvrbkvrxsjnvtoydwpkfatctzmzqibaozmhdlyacolqqenvonfrltkiznacvykzhzrhuqjyzmqilxgcepoltwnyejehluplxqjosoblqlibdnhunhzfbksqrsgnlfnpambqurwpmpfkfhxcjhtyqaunpxqlrmjbuscbnsafowwvichcarvkhuxvgiatrxgrnfrvdonpemzvahulaoghvpntaivqxaealrbbktgccwnzyoutgnfoqkglekkvuebxtpfevqvcdoxwfyodabzvvbcnrpltzlflismnjstpgwzydxhcdeagbsmiugedflxknpgmdnibnwfmfrdpyqhllchpxjstvvzwbtandnhvevczeynwgzmeczhcpmvzgsgvltitmoyevvdytplslbbyiovnoxkutzsgaseyzubrtycmusdsvkalqkdndzvadgcpdmdhjngiubmjabzuctkzvfesliupipvtqfhdgcexisgaysxjzusjmwftmjcissssicjmtfwmjsuzjxsyagsixecgdhfqtvpipuilsefvzktcuzbajmbuignjhdmdpcgdavzdndkqlakvsdsumcytrbuzyesagsztukxonvoiybblslptydvveyomtitlvgsgzvmpchzcemzgwnyezcvevhndnatbwzvvtsjxphcllhqypdrfmfwnbindmgpnkxlfdeguimsbgaedchxdyzwgptsjnmsilflztlprncbvvzbadoyfwxodcvqvefptxbeuvkkelgkqofngtuoyznwccgtkbbrlaeaxqviatnpvhgoaluhavzmepnodvrfnrgxrtaigvxuhkvrachcivwwofasnbcsubjmrlqxpnuaqythjcxhfkfpmpwruqbmapnflngsrqskbfzhnuhndbilqlbosojqxlpulhejeynwtlopecgxliqmzyjquhrzhzkyvcanziktlrfnovneqqlocayldhmzoabiqzmztctafkpwdyotvnjsxrvkbrvwnhajgloswnseaakncddqaqrullcgnhfdbqenuuokicmghkghyzqmeagldifpjwzunxgsrykwaeamqcxwfuxwllmmrargbjmxirbiiwvstvuikxxkavmeeisxccauvaaqjolpifwujjcwassvjwawbbndpkwgcjiynjnkekgtlnkytykdafgkkdiacstptljboivwgvpxzhxxqzlwnngtepumvbtgjlrfkqjcmkyorybgbykishdjyzgylgvjqtaykgowwukblyqfbhwjyfcslclrqyahwtdvqgvlqpyugykealjwfueguvmnfuwhnjkvsjxigssvfowwsfjhmraceyogvsikgprbsqdhnkvsfarbhyifpgfqyeeuvyfpydlxeiokawgxnxrdqdvmlknyjtyrncyclkfcrhnkyjkebwqxehjzszvesyffjodiqmvwbzxxygvpwcfzhdhcftyontopjqgagpjxomlqdcafjowxqdicmivsmwreyscrfcmggsxfpinuiodabtwancyuprksdibmtubmkjyojdwhbvopfrqatnkzdrjdvwenjvxicdlhtelhyjbbavmteefzqhtihdezzgufaifiighsgdipnokyprttxdciupxovvfefrarvjpimcjwmtdtgicpifcazgxxzqwwudkjvgdmdltskxfomrhjzqexlixnlmaahrveshwhptqewoxccuyuxfgrddvuazzubwptytbashrgddutwiaixphmthxwpetsdsymvemvdhlmgaleosjcieizimewauwgktltufjidfeluktmdsgvpmtstqjsklkejywqfukwcnxrlvazhumosewbnpgoztlouurgcjthbwqdztlynqmkvasjiipnuypgseammdxfgdnbhbxspovnilkjvamftfxertiqrvwkxdbufrgmyvfvbhdbxdjcaasvlwylhoiuaxdlmlwyzretjwbupgwcwnjaohpfsxscrpqkjtigqzjfcwjulycaohxerxhooxdxcwxjjzlzlgqvfmhqaodwvkvwlfcyvjnvmlyyiskctmqgrrbvptkjjobbyxmtnnvrhpokeqgjmtizcxfqixxdydnwawqkrnxwtuuvfjwrfumdhmcshfrnehbihiuilfafgzionyvzpowqhbmmtxivbaiblswmmdkiqfzbpgwgnhmmnkfewjoxbgxxsxkrxzwcuvnifbzvvggbvtrzujwwbnfvuhttpgiexserthqgsvbmyhuluvzacmtwfmlognxstwmkwfcgfobgsqsxpreynnuiinjzmhlpupketkkedndclbwvybpibhqmnhcrjzwynmcmpdpcmoswqgofxxhfgwlmkwkemkokxbldtozogmdzqmjnmaavdbctawoozrksrfwzavbofpmmjwgasejqddpipaajdixioabfpgwtafwfsalnvjouoldzjlpgbxskysftdhkcylmzhsjllqinvtbxdmsklcwyqdcfooihaixevaqpjczsltwkxaicupcyrckhlxdphyfvadwdvbvtshsvwgbuvouemgcslgpjvywrcerrbvppztbqvvfkrdalahfijiujhvxzvgmrmefhgufzbnypazcnskvrijfotciybsyzgajyfsohlncsshvwkokdxgaizqtzfzqpybptaifcqzkhhvofjuvehowjcepowywcxjlrqlttsimoirhiwwucpoywpvjuqwjfmcnzagdplooifhlredukonoixelvifsymtxngnivymiqnwxllsffogadlmndsuievowiqevbxpxwlhxlzhlmcprrvjrzbavrtbxlpspgpskrkieescrrnhmttctymiwwgmtwmmfdjyqyyrpewwhnfbxlsuhwsboyzhflowqcfrmdmntfzwgacfryqjikwxeqdayooholdirspfzbrggidqycgzhdfgvpccedplprjhhaoosqzuuoxajbwsjgyqzciykhkskbfxavqfxztyefkqzqxmocrudnodrmjklgojphhekgrbechrcsrfhdsjfrngthnntstpsdewolbkufmznwwntcmnigoifxchypayztvcyrgjsbtxvcoryhicolxgbczyeaflcykipnptzoingttkougldzbfmiwfwkmilxzlswpankzwjedehldsdcubphoedtftqtcgllgcmqkrgplnwopsgbahigpzdduphtpyhuwujduqdesjupqwjrcgiycvmdjzspqwblwgtleotoqfgksyqvzxmfwzokjensvimylqafavpymfaddjproejhesgyqgogxmmmlyjgaeudnetcqwfffwtrevnkfgjlegeahendhcpfokgzvcorjiycgxpphgyygnanwmiqahqnyghdmqrtjqachnvopuxtehsydkdhgwhlmopxluafqmajcttrfifjiqomqvlfqfafleqmesvdnjjtryhrplmwbfnqnyfkfunpenhzawebpypzvqzypuketpsayhujpbjvcfrnjvuapzislimnjwopfsezxitrxapbkwhrbobiyoiiqwxcfxqooixsxnquibmtzmuuoyptnadhkmoefaxdjhbeqgljwgutheuutqrhnpnuudlbtvbntfgsztwcczkiuidwzljhqtfqovfuxxwhkbudkbkslpvwimsbojlxnonjxzhacaonwkocuxqvoihaxjwpamuszaycprvcmrhkkxcbujmbmjvltukgwtxiykfknvenhszvnizwhlsbpryulfobckhnnwzxbfcgqydfrwscktmvcfksldljztqgmyobrmyovsyrnsjrrgjwoqpndlobrkbmsxajnhzifqwssmcjogcjqifqcoecbyjgothibvkkffxrshjsryzlfcpfekiyumjxdinqhpspeazztdfszivdxgbrnqvzmgnnbiivshyxtjnazdboqbyinimxkqqritbnuunqyzsukluczlgiwjxsviggzklvsifhtgqfqriktpofyuraoptxzengdthirugmaeofquughmvkejtvqotjgpqyfwrntvohskwihufixcjkhrxkjabkyigtybhuyvuxbyszaljwlliqpddfozhlucmitquxtgonoigrxfrqwrdpacyuyzcrnsfsojwbchhdruwpxwqeqkqpaqhgctcqmrkbeldgkfnrtwjjkenipdoqkuucygxyimgshqandkiyivzlclykfamvfvrwfkuqyhfelnpbyaidhqdcizzbtcotfmklghmeobijhglqaztgwjtjgutvsmhxxnoqmpbnuvuszjmmaclconprmcjgkrwtppsknbtxgxirxqwaljkkhlsbcgvuhbkqliewgtzlxjyumawwcgpuuspwysddtayirqxbntmmwkcqtbdxvogyigbdjwpqfsmgbqdgvgzmbgdkjckfdvrvzwqdjkvjemxyqirespcjieotqopmpdphyjiktmuwpythgqmrjbjpgqgyqlmschhqyyyuucusfaawobguieqpgjmvhqvdaznojiyhoechjqdmdzfxcaajygbwqyhmbjsqouysxsymvjoxsdgnjyoqhynrsznevnyilnxspgrktyojueewkprjlwumkqopnuskrtfwyczpygzrytazonwadlsjiqfqqzobgzvrsqzdtrjfaqhgsvwwzylqiuelwmoatwzqiohrneljktgvobqvbujyzdyxpcjutypnsbvvlmtoxpqjcxjmjlwovjxfptqlycbzphoojwlrwovrvrpnoqlzzfaqpfndlfdsdqzoskjwydgmgepuulysbzltneepkeecxgaosfeqezfxgenwnydgqohnmrfbekpgpynalfzuknxnbtfnztpxeceobzdsylfpjrjlbunizikkhapjswerilnxmgiupnpdllnuxlkcseybhuxzwyqmsxrnzlrbcjapzasvirwlrpldjcqjxcatweofsiemzzdnsckfjwginylmrhhmagljlaonqdzotisooqoorktdshuhkocfibikckrqqrsobjapwdgkhdkclawdsxdsajexuizkpooocyosdyrisgtqrwnmvchvusdvruswcmxlmgtnvrkaedikvxpbyytcthddidpiwqgukjiobtjixsladdrttxegixqyecybehoxkldrizbtflgyxwuzgfdijnptgzbalwbcicfqbdxgrvzxkxtvsgzrciyspzmdlzjserxzpbuotgtojqveouwbncfywtdarcaonuvralmonmgokjpznwdzfzmdseijbcpvlsmnxcrqepssimlixfkbwgeashuyyrrfnxudxuuyqiooqjiuqrkbemwaqjotrpuxgunlqrqlnpsfmjwitmevrgkcbqhorqqydsemwwthbvaifxrqbcdacyxsoespdvreupmoibbqaluyjguuaff'
  )
)
